# Generated by Django 5.2.3 on 2025-06-24 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(default='atiar', max_length=100),
        ),
    ]
